=== Zavr22/JavaXMLparser/commercial_offers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="commercial_offers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="commercial_offer" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="offer_name" type="xs:string"/>
                            <xs:element name="product">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="product_name" type="xs:string"/>
                                        <xs:element name="product_price" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="offer_price" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Zavr22/JavaXMLparser/commercial_offers.xml
<?xml version="1.0" encoding="UTF-8"?>
<commercial_offers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="commercial_offers.xsd">
    <commercial_offer>
        <offer_name>Commercial offer 1</offer_name>
        <product>
            <product_name>Optoma T500</product_name>
            <product_price>100</product_price>
        </product>
        <offer_price>200</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 3</offer_name>
        <product>
            <product_name>Optoma T600</product_name>
            <product_price>500</product_price>
        </product>
        <offer_price>500</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>300</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
    <commercial_offer>
        <offer_name>Commercial offer 2</offer_name>
        <product>
            <product_name>Optoma T400</product_name>
            <product_price>2</product_price>
        </product>
        <offer_price>300</offer_price>
    </commercial_offer>
</commercial_offers>
